import java.util.Properties;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        System.out.print("return aaaa bbb true ");
        Properties properties = System.getProperties();
        System.gc();
        return true;
    }
}
